### ISSUE TITLE
158.7-160.1 MHz shown as Marine for US.

### ISSUE THREAD

**Issue by isaacgerg** [Arrin-KN1E/SDRsharpbandplans#11]
This is used for public safety, industrial, and trunked.

**Comment by Arrin-KN1E** [comment]
Thanks again. I’ll be changing the more general allocations (e.g. Marine) to public safety and such when I have the time again. Sources are: public safety spectrum basic FCC page: https://www.fcc.gov/public-safety/public-safety-and-homeland-security/policy-and-licensing-division/public-safety-spectrum and the FCC table provided in the other thread.

**Comment by Arrin-KN1E** [comment]
I redid the 158.7-160.1MHz region to better reflect actual allocations. Marine is part of that area, so it was kept from 159.5 - 159.675MHz (NG155). Public safety and industrial/business are in the gap areas in between the mentioned marine, paging, and VHF Marine channels. I will keep the issue open for a few days in case you have any further comments.
