### ISSUE TITLE
28.4MHz is listed as phone but is 10m amateur band

### ISSUE THREAD

**Issue by isaacgerg** [Arrin-KN1E/SDRsharpbandplans#16]

**Comment by Arrin-KN1E** [comment]
@isaacgerg Phone is referring to the mode in the 10m amateur band (28.300-29.300MHz) per the ARRL Band plan: https://www.arrl.org/band-plan  
Used for all amateur bands listed in my band plans.  
I think that is what you were referring to. If I was wrong, let me know. 
I do see it needs some tidying up from 28.7 to 29.0 though. That might help.

**Comment by isaacgerg** [comment]
I am an amateur operator (w3idg).  On my display, it simply said "phone" and I saw nothing for 10m so i thought maybe it was wrong.  But, i see your call sign in your github name so you are also an ham.

**Comment by Arrin-KN1E** [comment]
@isaacgerg yes I am. Became one in 2019 because of SDR! 
Yeah, looking at it I think it would be a good idea for me to add parentheses to wide allocations within a band to avoid any future confusions. If you see more like that let me know.

**Comment by Arrin-KN1E** [comment]
@isaacgerg Latest update now shows which band you are in. Now it would display 'Phone (10m)'. I'll close this issue, since it should be this way on all bands now.
