### ISSUE TITLE
GQRX bandplan in CSV format

### ISSUE THREAD

**Issue by Defective4** [Arrin-KN1E/SDRsharpbandplans#21]
It would be nice to have a bandplan for [gqrx](https://github.com/gqrx-sdr/gqrx) SDR.
An example `bandplan.csv` file is available [here](https://gist.github.com/DallasEpperson/04daa6040cb41734a8b37acf6152ea06).
I can open a Pull Request with complete International/French/US bandplans if needed.

**Comment by Arrin-KN1E** [comment]
@Defective4 Looks like an easy adaptation. Feel free to open a pull request, as I'm not sure when I'll have the time to work on it on my own.

**Comment by Defective4** [comment]
Okay, done!

**Comment by Arrin-KN1E** [comment]
@Defective4 Thank you for the contribution! I'll be updating the README soon and the Gqrx comments in due time. Thanks again!
