### ISSUE TITLE
Many Bands default to Wide FM where another mode is used

### ISSUE THREAD

**Issue by MarsRaccoon** [Arrin-KN1E/SDRsharpbandplans#8]
It is very annoying to me, many of the bands do not have their mode set correctly, having the default be WFM is especially annoying because the bandwidth is so high. can assist in fixing if need to.

**Comment by Arrin-KN1E** [comment]
That is a valid point! I was going to address this in the next big update in a month or two. I was going to change the default to NFM. Anything you want to contribute is appreciated!

**Comment by Arrin-KN1E** [comment]
I apologize ahead of time since I'm still learning Github, so I don't really know what I'm doing; I think I did what I was supposed to. I made a branch called 'Mode-Adjust' for making mode changes. I made a bunch of simple WFM to NFM changes, obviously, you can add what you want from there.
